[GWC-1055] Out of memory due to premature rendering surface creation
GeoWebCache/geowebcache pull request #1056
Opened 2022-05-25 16:54 UTC by turingtestfail

added test

cleanup

2022-05-26 16:04 UTC, aaime requested changes

2022-05-27 19:56 UTC, turingtestfail commented on geowebcache/wms/src/main/java/org/geowebcache/service/wms/BufferedImageWrapper.java
> +public class BufferedImageWrapper {
fixed

2022-05-27 19:57 UTC, turingtestfail commented on geowebcache/wms/src/main/java/org/geowebcache/service/wms/WMSTileFuser.java
> +                bufferedImageWrapper.drawImage(tileImg, canvasx, canvasy); // imageObserver
fixed

2022-05-27 19:57 UTC, turingtestfail commented on geowebcache/wms/src/main/java/org/geowebcache/service/wms/WMSTileFuser.java
> +                // canvas creation
fixed

2022-05-27 19:57 UTC, turingtestfail commented on geowebcache/wms/src/main/java/org/geowebcache/service/wms/WMSTileFuser.java
> +                if (bufferedImageWrapper == null) {
fixed

2022-05-27 19:57 UTC, turingtestfail commented on geowebcache/wms/src/main/java/org/geowebcache/service/wms/BufferedImageWrapper.java
> +    public void setGfx(Graphics2D gfx) {
fixed

2022-05-27 19:57 UTC, turingtestfail commented on geowebcache/wms/src/test/java/org/geowebcache/service/wms/WMSTileFuserTest.java
> +                            if (count.getAndIncrement() == 0) {
fixed

2022-05-27 19:58 UTC, turingtestfail commented on geowebcache/wms/src/test/java/org/geowebcache/service/wms/WMSTileFuserTest.java
> +                                assertNull(tileFuser.bufferedImageWrapper);
fixed

2022-05-27 19:58 UTC, turingtestfail commented on geowebcache/wms/src/main/java/org/geowebcache/service/wms/BufferedImageWrapper.java
> +    public void setCanvas(BufferedImage canvas) {
fixed

2022-05-30 12:37 UTC, aaime commented on geowebcache/wms/src/test/java/org/geowebcache/service/wms/WMSTileFuserTest.java
> +                                count.incrementAndGet();
Double increment here: the first increment happened in the if, it happens whether the condition is matched, or not.

2022-05-30 16:57 UTC, merged

2022-05-30 16:57 UTC, aaime commented
Thanks! Can you backport to 2.21.x as well?