[GWC-1171] Improve handling special characters in the GWC Demos Page
GeoWebCache/geowebcache pull request #1173
Opened 2023-10-10 16:34 UTC by sikeoka

https://github.com/GeoWebCache/geowebcache/issues/1171
This PR updates the GWC Demos Page to properly escape special characters from GeoServer catalog information.  One thing to note here is that StringEscapeUtils::escapeEcmaScript is not secure when used in HTML attributes so the OWASP Encoder library is used instead.

2023-10-16 10:16 UTC, aaime requested changes
Looks overall good, one QA failure.

2023-10-16 20:08 UTC, sikeoka commented on geowebcache/core/src/main/java/org/geowebcache/demo/Demo.java
> -    @SuppressWarnings("PMD.AvoidPrintStackTrace")
Fixed.

2023-10-16 20:08 UTC, sikeoka commented
There was a Java heap space problem.

2023-11-06 10:18 UTC, aaime approved these changes

2023-11-06 10:18 UTC, merged

2023-11-06 10:18 UTC, aaime commented
The backport to `1.23.x` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
<details>
<summary>stderr</summary>

```
error: could not apply 49b26ff7... [GWC-1171] Improve handling special characters in the GWC Demos Page
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".

```
</details>

<details>
<summary>stdout</summary>

```
Auto-merging geowebcache/core/src/main/java/org/geowebcache/demo/Demo.java
CONFLICT (content): Merge conflict in geowebcache/core/src/main/java/org/geowebcache/demo/Demo.java

```
</details>

To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-1.23.x 1.23.x
# Navigate to the new working tree
cd .worktrees/backport-1.23.x
# Create a new branch
git switch --create backport-1173-to-1.23.x
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick 49b26ff7b0b49113d1e0ed3f45ffc52b094934eb
# Push it to GitHub
git push --set-upstream origin backport-1173-to-1.23.x
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-1.23.x
```
Then, create a pull request where the `base` branch is `1.23.x` and the `compare`/`head` branch is `backport-1173-to-1.23.x`.