Update old geowebcache.org links to geowebcache.osgeo.org
GeoWebCache/geowebcache pull request #1341
Opened 2024-12-29 10:54 UTC by petersmythe

Except for schema URLs e.g. http://geowebcache.org/schema/1.9.0/geowebcache.xsd

Also reorder GetCapabilities links in http://localhost:8080/geoserver/gwc/home, so that **latter** refers to the correct (WMS) GetCapabilities:

![image](https://github.com/user-attachments/assets/d9262633-cb4b-4f5c-8ccc-fbde9f58c113)

2024-12-29 11:28 UTC, petersmythe commented on documentation/en/user/source/production/index.rst
> +Also see <del>http://geowebcache.org/trac/wiki/resources</del> for tools that can be used to estimate how much storage you need and how long seeding will take
I can't find an update for `/trac/wiki/resources`, so have chosen to strike this out until it can be found.

2025-01-07 22:36 UTC, jodygarnett requested changes
Small change to address trac wiki link

2025-01-07 22:36 UTC, jodygarnett commented on documentation/en/user/source/production/index.rst
> +Also see <del>http://geowebcache.org/trac/wiki/resources</del> for tools that can be used to estimate how much storage you need and how long seeding will take
I do not think we are going to find that one! But the internet remembers:

http://web.archive.org/web/20100326130953/http://geowebcache.org/trac/wiki/resources

The spreadsheet is lost to time but I added the table to our wiki here https://github.com/GeoWebCache/geowebcache/wiki/Estimating-the-number-of-tiles-and-size-on-disk

2025-01-07 22:36 UTC, jodygarnett commented on documentation/en/user/source/production/index.rst
> +Also see <del>http://geowebcache.org/trac/wiki/resources</del> for tools that can be used to estimate how much storage you need and how long seeding will take
```suggestion
Also see https://github.com/GeoWebCache/geowebcache/wiki/Estimating-the-number-of-tiles-and-size-on-disk for table that can be used to estimate how much storage you need and how long seeding will take
```

2025-01-08 08:51 UTC, petersmythe commented on documentation/en/user/source/production/index.rst
> +Also see <del>http://geowebcache.org/trac/wiki/resources</del> for tools that can be used to estimate how much storage you need and how long seeding will take
Wow, thank you!

2025-01-08 08:52 UTC, merged